<wsdl:definitions name="RakeReadProocess" targetNamespace="http://xmlns.oracle.com/CTMSAPICCLS/RakeReadOperation/RakeReadProocess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/CTMSAPICCLS/RakeReadOperation/RakeReadProocess" xmlns:ns1="http://www.concor.com/cil/RakeRead/1.0/" xmlns:ns2="http://www.concor.com/cil/RakeWrite/1.0/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <wsdl:documentation>
      <abstractWSDL>http://10.1.100.101:8002/soa-infra/services/default/RakeReadOperation!3.0/WSDLs/RakeReadProocess.wsdl</abstractWSDL>
   </wsdl:documentation>
   <plnk:partnerLinkType name="RakeReadProocess">
      <plnk:role name="RakeReadProocessProvider" portType="client:RakeReadProocess"/>
   </plnk:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://www.concor.com/cil/RakeRead/1.0/" schemaLocation="http://10.1.100.101:8002/soa-infra/services/default/RakeReadOperation/rakereadproocess_client_ep?XSD=../Schemas/Input.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://www.concor.com/cil/RakeWrite/1.0/" schemaLocation="http://10.1.100.101:8002/soa-infra/services/default/RakeReadOperation/rakereadproocess_client_ep?XSD=../Schemas/Output.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="RakeReadProocessRequestMessage">
      <wsdl:part name="payload" element="ns1:RakeRead"/>
   </wsdl:message>
   <wsdl:message name="RakeReadProocessResponseMessage">
      <wsdl:part name="payload" element="ns2:RakeWriteOutput"/>
   </wsdl:message>
   <wsdl:portType name="RakeReadProocess">
      <wsdl:operation name="process">
         <wsdl:input message="client:RakeReadProocessRequestMessage"/>
         <wsdl:output message="client:RakeReadProocessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="RakeReadProocessBinding" type="client:RakeReadProocess">
      <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="process">
         <soap:operation style="document" soapAction="process"/>
         <wsdl:input>
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output>
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="rakereadproocess_client_ep">
      <wsdl:port name="RakeReadProocess_pt" binding="client:RakeReadProocessBinding">
         <soap:address location="http://10.1.100.101:8002/soa-infra/services/default/RakeReadOperation/rakereadproocess_client_ep"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
