<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="CWHImportCrgDSTFWriteBPEL" targetNamespace="http://xmlns.oracle.com/CTMSAPI/CWHImportCrgDSTFWrite/CWHImportCrgDSTFWriteBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/CTMSAPI/CWHImportCrgDSTFWrite/CWHImportCrgDSTFWriteBPEL" xmlns:ns1="http://www.concor.com/cil/ImprtCrgDstuffWrite/1.0/" xmlns:ns2="http://www.concor.com/cil/ImprtCrgDstuffWrite/1.0/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:documentation>
    <abstractWSDL>http://10.1.100.101:8002/soa-infra/services/default/CWHImportCrgDSTFWrite!1.0/WSDLs/CWHImportCrgDSTFWriteBPEL.wsdl</abstractWSDL>
  </wsdl:documentation>
  <plnk:partnerLinkType name="CWHImportCrgDSTFWriteBPEL">
    <plnk:role name="CWHImportCrgDSTFWriteBPELProvider" portType="client:CWHImportCrgDSTFWriteBPEL"/>
  </plnk:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://www.concor.com/cil/ImprtCrgDstuffWrite/1.0/" schemaLocation="cwhimportcrgdstfwritebpel_client_ep.xsd"/>
    </schema>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://www.concor.com/cil/ImprtCrgDstuffWrite/1.0/" schemaLocation="cwhimportcrgdstfwritebpel_client_1.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="CWHImportCrgDSTFWriteBPELRequestMessage">
    <wsdl:part name="payload" element="ns1:ImprtCrgDstuffWriteInput"/>
  </wsdl:message>
  <wsdl:message name="CWHImportCrgDSTFWriteBPELResponseMessage">
    <wsdl:part name="payload" element="ns1:ImprtCrgDstuffWriteOutput"/>
  </wsdl:message>
  <wsdl:portType name="CWHImportCrgDSTFWriteBPEL">
    <wsdl:operation name="process">
      <wsdl:input message="client:CWHImportCrgDSTFWriteBPELRequestMessage"/>
      <wsdl:output message="client:CWHImportCrgDSTFWriteBPELResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CWHImportCrgDSTFWriteBPELBinding" type="client:CWHImportCrgDSTFWriteBPEL">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="process">
      <soap:operation style="document" soapAction="process"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="cwhimportcrgdstfwritebpel_client_ep">
    <wsdl:port name="CWHImportCrgDSTFWriteBPEL_pt" binding="client:CWHImportCrgDSTFWriteBPELBinding">
      <soap:address location="http://10.1.100.101:8002/soa-infra/services/default/CWHImportCrgDSTFWrite/cwhimportcrgdstfwritebpel_client_ep"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>