INSERT INTO TT_COUTWTRDTLS (WTR_NO,WGN_NO,WGN_LIFE_NO,CTR_NO,CTR_LIFE_NO,CTR_ISO_CD,CTR_STAT,CTR_SIZE,CTR_TYPE,
CRG_TYPE,LDD_MT_FLG,IMP_EXP_FLG,SLINE_CD,GW_PORT_CD,ACTY_CD,DT_ARR_DEP,TM_OPN,ERR_FLG,CTR_DMG_FLG,SEAL_STAT,
CNCL_FLG,TRNS_DT_TM,USER_ID,SEAL_NO,DMG_CODE,LDG_PMT_NO,WGN_DMG_FLG,LJO,TO_LOC) VALUES 
(:wtr_no,:wagon_number,SYSDATE,:container_number, SYSDATE ,:iso_code,'E4',:container_size,:container_type,
NULL,'E','X',:sline_code,'PPSP','LR',SYSDATE ,NULL,'D','N','I',
NULL,SYSDATE,'TEST',:seal_number,NULL,NULL,'N',NULL,'TKD')
