INSERT INTO TT_CINADVCTR (CTR_NO,CTR_LIFE_NO,SLINE_CD,CTR_ISO_CD,CTR_SIZE,
CTR_TYPE,CRG_TYPE,LDD_MT_FLG,FCL_LCL_FLG,STN_CD,TRN_NO,WGN_NO,WGN_TYPE,GW_PORT_CD,
CTR_STG_FLG,ERR_FLG,REC_NO,CTR_IWB_FLG,RMRK,CNCL_FLG,TRNS_DT_TM,USER_ID,WGN_LIFE_NO,
SMTP_NO,SMTP_DT,CTR_WT,PORT_NAM,TRN_DEP) VALUES 
(:container_number,TO_DATE(to_char(sysdate,'DD-MM-YYYY'),'DD-MM-YYYY'),'CMCGM',NULL,40,'GL','N','L','FCL','TKD','TRN7007678',
:wagon_number,'I','MDPT','A',NULL,:wagon_id,'C',NULL,NULL, sysdate,'TEST',TO_DATE(to_char(sysdate,'DD-MM-YYYY'),'DD-MM-YYYY'),
'1630',TO_DATE('2007-12-12 00:00:00','YYYY-MM-DD HH24:MI:SS'),24.3,'MDPT',
 TO_DATE(to_char(sysdate-2,'DD-MM-YYYY'),'DD-MM-YYYY'))