from app import postgres_db as db
from datetime import datetime

class CCLSRake(db.Model):
    id =  db.Column(db.BigInteger(), primary_key=True)
    rake_id = db.Column(db.BigInteger())
    train_number = db.Column(db.String(10))
    train_origin_station = db.Column(db.String(25))
    train_destination_station = db.Column(db.String(25))
    rake_type = db.Column(db.String(5))
    rake_number = db.Column(db.String(25))
    wagon_type =  db.Column(db.String(3))
    wagon_number = db.Column(db.BigInteger())
    wagon_sequence_number = db.Column(db.Integer())
    wagon_ldd_mt = db.Column(db.String(1), nullable=True)
    wagon_owner = db.Column(db.String(25))
    container_number = db.Column(db.String(11))
    container_life_number = db.Column(db.DateTime()) 
    container_size = db.Column(db.Integer())
    container_type = db.Column(db.String(2))
    container_status = db.Column(db.String(2))
    container_gross_weight = db.Column(db.Float())
    container_origin_station = db.Column(db.String(25))
    container_destination_station = db.Column(db.String(25))
    iso_code = db.Column(db.String(25))
    container_stg_flag = db.Column(db.String(1), nullable=True)
    container_iwb_flag = db.Column(db.String(1), nullable=True)
    cargo_type = db.Column(db.String(25))
    fcl_lcl_flg = db.Column(db.String(3), nullable=True)
    station_cd = db.Column(db.String(25))
    gw_port_cd = db.Column(db.String(25))
    error_flg = db.Column(db.String(1), nullable=True)
    remark = db.Column(db.String(100))
    cancel_flg = db.Column(db.String(1), nullable=True)
    trans_date = db.Column(db.DateTime())
    user_id = db.Column(db.String(100))
    wagon_life_number = db.Column(db.DateTime())
    smtp_no = db.Column(db.String(25))
    smtp_date = db.Column(db.DateTime())
    port_name = db.Column(db.String(25))
    train_dept = db.Column(db.DateTime())
    seal_number = db.Column(db.String(10))
    hazardious_status = db.Column(db.String(2))
    sline_code = db.Column(db.String(6))
    attribute_1 = db.Column(db.String(25))
    attribute_2 = db.Column(db.String(25))
    attribute_3 = db.Column(db.String(25))
    attribute_4 = db.Column(db.String(25))
    attribute_5 = db.Column(db.String(25))
    attribute_6 = db.Column(db.DateTime())
    attribute_7 = db.Column(db.DateTime())
    created_date = db.Column(db.DateTime(), default = datetime.now)
    created_by = db.Column(db.String(25))
    updated_date = db.Column(db.DateTime(), default = datetime.now, onupdate=datetime.now)
    updated_by = db.Column(db.String(25))
    date_actual_departure =  db.Column(db.DateTime())
    ldd_mt_flg = db.Column(db.String(2))
    imp_exp_flg = db.Column(db.String(1), nullable=True)
    adv_boe_flg = db.Column(db.String(2), nullable=True)
    error_msg = db.Column(db.String(100))
    status_flg = db.Column(db.String(1), nullable=True)
    track_number = db.Column(db.String(10), nullable=True)
    
    __tablename__ = 'xxccls_rake_trnsdtls_tbl'