from app import postgres_db as db
from datetime import datetime

class CCLSRake(db.Model):
    id =  db.Column(db.BigInteger(), primary_key=True)
    rake_id = db.Column(db.BigInteger())
    train_number = db.Column(db.String(10))
    train_origin_station = db.Column(db.String(25))
    train_destination_station = db.Column(db.String(25))
    rake_type = db.Column(db.String(5))
    rake_number = db.Column(db.String(25))
    wagon_type =  db.Column(db.String(3))
    wagon_number = db.Column(db.BigInteger())
    wagon_sequence_number = db.Column(db.Integer())
    wagon_ldd_mt = db.Column(db.String(1), nullable=True)
    wagon_owner = db.Column(db.String(25))
    container_number = db.Column(db.String(11))
    container_life_number = db.Column(db.DateTime()) 
    container_size = db.Column(db.Integer())
    container_type = db.Column(db.String(2))
    container_stat = db.Column(db.String(20))
    container_gross_weight = db.Column(db.Float())
    container_origin_station = db.Column(db.String(25))
    container_destination_station = db.Column(db.String(25))
    iso_code = db.Column(db.String(25))
    container_stg_flag = db.Column(db.String(1), nullable=True)
    container_iwb_flag = db.Column(db.String(1), nullable=True)
    cargo_type = db.Column(db.String(25))
    fcl_lcl_flg = db.Column(db.String(3), nullable=True)
    station_cd = db.Column(db.String(25))
    gw_port_cd = db.Column(db.String(25))
    error_flg = db.Column(db.String(1), nullable=True)
    remark = db.Column(db.String(100))
    cancel_flg = db.Column(db.String(1), nullable=True)
    trans_date = db.Column(db.DateTime())
    user_id = db.Column(db.String(100))
    wagon_life_number = db.Column(db.DateTime())
    smtp_no = db.Column(db.String(25))
    smtp_date = db.Column(db.DateTime())
    port_name = db.Column(db.String(25))
    train_dept = db.Column(db.DateTime())
    seal_number = db.Column(db.String(10))
    hazardious_status = db.Column(db.String(20))
    sline_code = db.Column(db.String(6))
    attribute_1 = db.Column(db.String(25))
    attribute_2 = db.Column(db.String(25))
    attribute_3 = db.Column(db.String(25))
    attribute_4 = db.Column(db.String(25))
    attribute_5 = db.Column(db.String(25))
    attribute_6 = db.Column(db.DateTime())
    attribute_7 = db.Column(db.DateTime())
    created_date = db.Column(db.DateTime(), default = datetime.now)
    created_by = db.Column(db.String(25))
    updated_date = db.Column(db.DateTime(), default = datetime.now, onupdate=datetime.now)
    updated_by = db.Column(db.String(25))
    date_actual_departure =  db.Column(db.DateTime())
    ldd_mt_flg = db.Column(db.String(2))
    imp_exp_flg = db.Column(db.String(1), nullable=True)
    adv_boe_flg = db.Column(db.String(2), nullable=True)
    error_msg = db.Column(db.String(100))
    status_flg = db.Column(db.String(1), nullable=True)
    track_number = db.Column(db.String(10), nullable=True)
    comm_desc = db.Column(db.String(25))
    comm_type = db.Column(db.String(25))
    final_destination =  db.Column(db.String(25))
    importer_name =  db.Column(db.String(200))
    location =  db.Column(db.String(25))
    rec_no = db.Column(db.String(25))
    
    __tablename__ = 'xxccls_rake_trnsdtls_tbl'


class DomesticContainers(db.Model):
    id =  db.Column(db.BigInteger(), primary_key=True)
    rake_id = db.Column(db.BigInteger())
    rake_type = db.Column(db.String(5))
    train_id = db.Column(db.String(25))
    train_number = db.Column(db.String(25))
    rake_number = db.Column(db.String(10))
    station_from = db.Column(db.String(10))
    station_to = db.Column(db.String(10))
    crntsttn = db.Column(db.String(10))
    rake_pcml_flag = db.Column(db.String(5))
    withdrawl_time = db.Column(db.DateTime())
    destination_plct_time = db.Column(db.DateTime())
    line_number = db.Column(db.String(10))
    rlsd_time = db.Column(db.DateTime())
    wagon_number = db.Column(db.String(15))
    wagon_type = db.Column(db.String(10))
    sequence_number = db.Column(db.Float())
    wagon_ldd_mt = db.Column(db.String(5))
    top_bottom_flag = db.Column(db.String(5))
    man_wagon_cc = db.Column(db.Float())
    container_id = db.Column(db.String(30))
    container_number = db.Column(db.String(15))
    iso_code = db.Column(db.String(10))
    container_size = db.Column(db.Float())
    container_type = db.Column(db.String(10))
    container_stat = db.Column(db.String(20))
    container_from_station = db.Column(db.String(10))
    container_to_station = db.Column(db.String(10))
    ldd_mt_flg = db.Column(db.String(5))
    commodity_code = db.Column(db.String(10))
    seal_number = db.Column(db.String(25))
    mac_hazard_flag = db.Column(db.String(5))
    container_net_weight = db.Column(db.Float())
    container_gross_weight = db.Column(db.Float())
    trans_date = db.Column(db.DateTime())
    track_number = db.Column(db.String(10), nullable=True)
    created_date = db.Column(db.DateTime(), default = datetime.now)
    created_by = db.Column(db.String(25))
    updated_date = db.Column(db.DateTime(), default = datetime.now, onupdate=datetime.now)
    updated_by = db.Column(db.String(25))


class MissedInwardContainers(db.Model):
    id =  db.Column(db.BigInteger(), primary_key=True)
    rake_id = db.Column(db.BigInteger(), nullable=True)
    train_number = db.Column(db.String(10), nullable=True)
    rake_number = db.Column(db.String(25), nullable=True)
    rake_type = db.Column(db.String(5), nullable=True)
    wagon_number = db.Column(db.BigInteger(), nullable=True)
    wagon_sequence_number = db.Column(db.Integer(), nullable=True)
    container_number = db.Column(db.String(11))
    container_life_number = db.Column(db.DateTime(), nullable=True) 
    container_size = db.Column(db.Integer(), nullable=True)
    container_type = db.Column(db.String(2), nullable=True)
    container_stat = db.Column(db.String(2), nullable=True)
    container_gross_weight = db.Column(db.Float(),nullable=True)
    container_destination_station = db.Column(db.String(25),nullable=True)
    iso_code = db.Column(db.String(25), nullable=True)
    gw_port_cd = db.Column(db.String(25), nullable=True)
    trans_date = db.Column(db.DateTime(), nullable=True)
    wagon_life_number = db.Column(db.DateTime(), nullable=True)
    seal_number = db.Column(db.String(10), nullable=True)
    hazardious_status = db.Column(db.String(2), nullable=True)
    sline_code = db.Column(db.String(6), nullable=True)
    attribute_1 = db.Column(db.String(25), nullable=True)
    attribute_2 = db.Column(db.String(25), nullable=True)
    attribute_3 = db.Column(db.String(25), nullable=True)
    created_date = db.Column(db.DateTime(), default = datetime.now)
    created_by = db.Column(db.String(25), nullable=True)
    updated_date = db.Column(db.DateTime(), default = datetime.now, onupdate=datetime.now)
    updated_by = db.Column(db.String(25), nullable=True)
    ldd_mt_flg = db.Column(db.String(2), nullable=True)
    imp_exp_flg = db.Column(db.String(1), nullable=True)
    track_number = db.Column(db.String(10), nullable=True)
    trans_type = db.Column(db.String(10), nullable=True)